### ISSUE TITLE
Add ..getvowel so I can make a word with a crap hand

### ISSUE THREAD

**Issue by maxsaltonstall** [maxsaltonstall/letters-with-strangers#159]
Add new command
getvowel (..getvowel) that returns A, E, I, O or U and no other possible letters.
Costs more than 'get'
5 glyphs?

**Comment by Wyatt-Stanke** [comment]
Sounds good. Should you get a Y?

**Comment by maxsaltonstall** [comment]
I'm thinking no, because it's not that helpful when your hand is full of G,
C, M, R
I'd want a vowel that's more versatile.

>
