### ISSUE TITLE
simplify `emoji_letter`

### ISSUE THREAD

**Issue by davidstanke** [maxsaltonstall/letters-with-strangers#190]
[this method](https://github.com/maxsaltonstall/letters-with-strangers/blob/e29031bbc0a18a3b49923584352c597de4eee216/bot/models/util/string_util.py#L18) is a hard-to-read and overly obscure way to make an emoji out of a letter, when we could instead just surround the letter with colons:

`:a:` --> 🅰️ 
`:b:` --> 🅱️ 
..etc

**Comment by Wyatt-Stanke** [comment]
A is not actually :a: on discord, it is :regional_indicator_a:
